<?php

namespace Disjfa\MozaicBundle\Entity;

use Doctrine\DBAL\LockMode;
use Doctrine\ORM\EntityRepository;

/**
 * UnsplashUserRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnsplashUserRepository extends EntityRepository
{
    /**
     * @param string $id
     * @param null   $lockMode
     * @param null   $lockVersion
     */
    public function find(mixed $id, LockMode|int|null $lockMode = null, ?int $lockVersion = null): ?object
    {
        return $this->findOneBy(['unsplashId' => $id]);
    }
}
