<?php

namespace Disjfa\MozaicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPhotoRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserPhotoRepository extends EntityRepository
{
    /**
     * @return UserPhoto[]
     */
    public function findByMyPhotos($userId)
    {
        $qb = $this->createQueryBuilder('user_photo');
        $qb->where('user_photo.userId = :userId');
        $qb->setParameter('userId', $userId);

        $qb->orderBy('user_photo.dateFinished', 'DESC');
        $qb->setMaxResults(30);

        return $qb->getQuery()->getResult();
    }
}
